name: touchscreening_fixed
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
 sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  flutter_tts: ^4.2.2
  pdf: ^3.10.1
  printing: ^5.11.0
 
  # Ícones estilo Cupertino para iOS
  cupertino_icons: ^1.0.8

  # Gerenciamento de estado
  provider: ^6.0.5

  # banco de dados
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8


  # Manipulação de caminhos de arquivos
  path: ^1.9.0

  # Armazenamento local leve (SharedPreferences)
  shared_preferences: ^2.3.5

  # Validação de formulários
  flutter_form_builder: ^10.0.1
  google_sign_in: ^6.3.0
  connectivity_plus: ^6.1.4
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Regras de lint recomendadas
  flutter_lints: ^6.0.0

  # Build runner para geração de código
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  # Adicionar assets aqui
  assets:
    - lib/assets/images/LOGO2.png
    - lib/assets/images/LOGO4.png
   # - lib/assets/images/LOGO5.png
    - lib/assets/images/LOGO1.png
    - lib/assets/images/logo.png